# Generated by Django 5.0.6 on 2024-07-13 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='task_closed_by',
        ),
        migrations.RemoveField(
            model_name='taskdetails',
            name='task_created_by',
        ),
        migrations.AddField(
            model_name='taskdetails',
            name='task_closed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='closed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdetails',
            name='task_created',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
